data:extend(
{

{
	type = "item",
	name = "magic-assembling-machine-1",
	icon = "__Thaumaturgic-Machinations__/graphics/icons/item/magic-assembling-machine-1.png",
	icon_size = 32,
	flags = {"goes-to-quickbar"},
	subgroup = "production-machine",
	order = "b[magic-assembling-machine]",
	place_result = "magic-assembling-machine-1",
	stack_size = 50,
},
{
	type = "item",
	name = "magic-assembling-machine-2",
	icon = "__Thaumaturgic-Machinations__/graphics/icons/item/magic-assembling-machine-2.png",
	icon_size = 32,
	flags = {"goes-to-quickbar"},
	subgroup = "production-machine",
	order = "b[magic-assembling-machine]",
	place_result = "magic-assembling-machine-2",
	stack_size = 50,
},
{
	type = "item",
	name = "temp-aspect-machine",
	icon = "__base__/graphics/icons/chemical-plant.png",
	icon_size = 32,
	flags = {"goes-to-quickbar"},
	subgroup = "production-machine",
	order = "e[chemical-plant]",
	place_result = "temp-aspect-machine",
	stack_size = 10,
},
{
	type = "item",
	name = "TM-lab",
	icon = "__Thaumaturgic-Machinations__/graphics/icons/item/TM-lab.png",
	icon_size = 32,
	flags = {"goes-to-quickbar"},
	subgroup = "production-machine",
	order = "g[TM-lab]",
	place_result = "TM-lab",
	stack_size = 10,
},
{
	type = "item",
	name = "temp-thaumic-tree-farm",
	icon = "__base__/graphics/icons/oil-refinery.png",
	icon_size = 32,
	flags = {"goes-to-quickbar"},
	subgroup = "production-machine",
	order = "y",
	place_result = "temp-thaumic-tree-farm",
	stack_size = 10,
},
{
	type = "item",
	name = "alumentum",
	icon = "__Thaumaturgic-Machinations__/graphics/icons/item/alumentum.png",
	icon_size = 32,
	flags = {"goes-to-main-inventory"},
	fuel_category = "chemical",
	fuel_value = "20MJ",
	fuel_acceleration_multiplier = 1.1,
	fuel_top_speed_multiplier = 1,
	subgroup = "raw-material",
	order = "alumentum",
	stack_size = 50,
},
{
	type = "item",
	name = "gravestone",
	icon = "__Thaumaturgic-Machinations__/graphics/icons/item/gravestone.png",
	icon_size = 32,
	flags = {"goes-to-main-inventory"},
	subgroup = "raw-material",
	order = "gravestone",
	stack_size = 50,
},
{
	type = "item",
	name = "magic-gear-wheel",
	icon = "__Thaumaturgic-Machinations__/graphics/icons/item/magic-gear-wheel.png",
	icon_size = 32,
	flags = {"goes-to-main-inventory"},
	subgroup = "raw-material",
	order = "magic-gear-wheel",
	stack_size = 100,
},
{
	type = "item",
	name = "manasteel",
	icon = "__Thaumaturgic-Machinations__/graphics/icons/item/manasteel.png",
	icon_size = 32,
	flags = {"goes-to-main-inventory"},
	subgroup = "raw-material",
	order = "manasteel",
	stack_size = 100,
},
{
	type = "item",
	name = "refined-silverwood",
	icon = "__Thaumaturgic-Machinations__/graphics/icons/item/refined-silverwood.png",
	icon_size = 32,
	flags = {"goes-to-main-inventory"},
	fuel_category = "Vis",
	fuel_value = "15MJ",
	subgroup = "raw-material",
	order = "silverwood-3",
	stack_size = 100,
},
{
	type = "item",
	name = "vis-diode",
	icon = "__Thaumaturgic-Machinations__/graphics/icons/item/vis-diode.png",
	icon_size = 32,
	flags = {"goes-to-main-inventory"},
	subgroup = "raw-material",
	order = "vis-diode",
	stack_size = 50,
},
{
	type = "item",
	name = "vis-infused-brick",
	icon = "__Thaumaturgic-Machinations__/graphics/icons/item/vis-infused-brick.png",
	icon_size = 32,
	flags = {"goes-to-main-inventory"},
	subgroup = "raw-material",
	order = "vis-infused-brick",
	stack_size = 100,
},
{
	type = "item",
	name = "vis-infused-wood",
	icon = "__Thaumaturgic-Machinations__/graphics/icons/item/vis-infused-wood.png",
	icon_size = 32,
	flags = {"goes-to-main-inventory"},
	fuel_category = "Vis",
	fuel_value = "4MJ",
	subgroup = "raw-material",
	order = "vis-infused-wood",
	stack_size = 100,
},
{
	type = "item",
	name = "catalytic-coal",
	icon = "__Thaumaturgic-Machinations__/graphics/icons/item/catalytic-coal.png",
	icon_size = 32,
	flags = {"goes-to-main-inventory"},
	fuel_category = "Vis",
	fuel_value = "12MJ",
	subgroup = "raw-resource",
	order = "b[coal]",
	stack_size = 50,
},
{
	type = "item",
	name = "all-shard",
	icon = "__Thaumaturgic-Machinations__/graphics/icons/item/all-shard.png",
	icon_size = 32,
	flags = {"goes-to-main-inventory"},
	subgroup = "raw-resource",
	order = "shard-1",
	stack_size = 100,
},
{
	type = "item",
	name = "air-shard",
	icon = "__Thaumaturgic-Machinations__/graphics/icons/item/air-shard.png",
	icon_size = 32,
	flags = {"goes-to-main-inventory"},
	subgroup = "raw-resource",
	order = "shard-2",
	stack_size = 100,
},
{
	type = "item",
	name = "earth-shard",
	icon = "__Thaumaturgic-Machinations__/graphics/icons/item/earth-shard.png",
	icon_size = 32,
	flags = {"goes-to-main-inventory"},
	subgroup = "raw-resource",
	order = "shard-3",
	stack_size = 100,
},
{
	type = "item",
	name = "fire-shard",
	icon = "__Thaumaturgic-Machinations__/graphics/icons/item/fire-shard.png",
	icon_size = 32,
	flags = {"goes-to-main-inventory"},
	subgroup = "raw-resource",
	order = "shard-4",
	stack_size = 100,
},
{
	type = "item",
	name = "water-shard",
	icon = "__Thaumaturgic-Machinations__/graphics/icons/item/water-shard.png",
	icon_size = 32,
	flags = {"goes-to-main-inventory"},
	subgroup = "raw-resource",
	order = "shard-5",
	stack_size = 100,
},
{
	type = "item",
	name = "law-shard",
	icon = "__Thaumaturgic-Machinations__/graphics/icons/item/law-shard.png",
	icon_size = 32,
	flags = {"goes-to-main-inventory"},
	subgroup = "raw-resource",
	order = "shard-6",
	stack_size = 100,
},
{
	type = "item",
	name = "entropy-shard",
	icon = "__Thaumaturgic-Machinations__/graphics/icons/item/entropy-shard.png",
	icon_size = 32,
	flags = {"goes-to-main-inventory"},
	subgroup = "raw-resource",
	order = "shard-7",
	stack_size = 100,
},
{
	type = "item",
	name = "silverwood-seedling",
	icon = "__Thaumaturgic-Machinations__/graphics/icons/item/silverwood-seedling.png",
	icon_size = 32,
	flags = {"goes-to-main-inventory"},
	subgroup = "raw-resource",
	order = "silverwood-1",
	stack_size = 100,
},
{
	type = "item",
	name = "raw-silverwood",
	icon = "__Thaumaturgic-Machinations__/graphics/icons/item/raw-silverwood.png",
	icon_size = 32,
	flags = {"goes-to-main-inventory"},
	fuel_category = "Vis",
	fuel_value = "10MJ",
	subgroup = "raw-resource",
	order = "silverwood-2",
	stack_size = 100,
},
{
	type = "item",
	name = "crucible",
	icon = "__Thaumaturgic-Machinations__/graphics/icons/item/crucible.png",
	icon_size = 32,
	flags = {"goes-to-quickbar"},
	subgroup = "smelting-machine",
	order = "a[crucible-1]",
	place_result = "crucible",
	stack_size = 50,
},
{
	type = "item",
	name = "crucible-2",
	icon = "__Thaumaturgic-Machinations__/graphics/icons/item/crucible-2.png",
	icon_size = 32,
	flags = {"goes-to-quickbar"},
	subgroup = "smelting-machine",
	order = "a[crucible-2]",
	place_result = "crucible-2",
	stack_size = 50,
},
{
	type = "item",
	name = "infused-thaumic-stone-furnace",
    icon = "__Thaumaturgic-Machinations__/graphics/icons/entity/infused_thaumic_furnace.png",
	icon_size = 32,
	flags = {"goes-to-quickbar"},
	subgroup = "smelting-machine",
	order = "a[stone-furnace-2]",
	place_result = "infused-thaumic-stone-furnace",
	stack_size = 50,
},
{
	type = "item",
	name = "thaumic-stone-furnace",
	icon = "__Thaumaturgic-Machinations__/graphics/icons/entity/thaumic_furnace.png",
	icon_size = 32,
	flags = {"goes-to-quickbar"},
	subgroup = "smelting-machine",
	order = "a[stone-furnace-1]",
	place_result = "thaumic-stone-furnace",
	stack_size = 50,
},

{
	type = "item",
	name = "soulfire",
	icon = "__Thaumaturgic-Machinations__/graphics/icons/item/soulfire.png",
	icon_size = 32,
	flags = {"goes-to-main-inventory"},
	fuel_category = "Vis",
	fuel_value = "50MJ",
	subgroup = "raw-material",
	order = "c[soulfire]",
	stack_size = 50
},
{
	type = "item",
	name = "prismatic-fuel",
	icon = "__Thaumaturgic-Machinations__/graphics/icons/item/prismatic-fuel.png",
	icon_size = 32,
	flags = {"goes-to-main-inventory"},
	fuel_category = "chemical",
	fuel_value = "50MJ",
	fuel_acceleration_multiplier = 2.5,
	fuel_top_speed_multiplier = 1.5,
	subgroup = "raw-material",
	order = "c[prismatic-fuel]",
	stack_size = 50
},
{
	type = "item",
	name = "dark-electronic-circuit",
	icon = "__Thaumaturgic-Machinations__/graphics/icons/item/dark-electronic-circuit.png",
	icon_size = 32,
	flags = {"goes-to-main-inventory"},
	subgroup = "intermediate-product",
	order = "g[q]",
	stack_size = 100,
},
})