if not data.raw.item["seedling"] then
data:extend({
  {
    type = "item",
	name = "seedling",
	icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
	flags = {"goes-to-main-inventory"},
	subgroup = "raw-material",
	order = "seedling",
	stack_size = 100,
  },
})
end

data:extend({

  
  {
    type = "item",
    name = "catalytic-coal",
    icon = "__base__/graphics/icons/coal.png",
    dark_background_icon = "__base__/graphics/icons/coal-dark-background.png",
    flags = {"goes-to-main-inventory"},
    fuel_category = "Vis",
    fuel_value = "8MJ",
    subgroup = "raw-resource",
    order = "b[coal]",
    stack_size = 50
  },
  {
    type = "item",
    name = "thaumic-stone-furnace",
    icon = "__base__/graphics/icons/stone-furnace.png",
    flags = {"goes-to-quickbar"},
    subgroup = "smelting-machine",
    order = "a[stone-furnace]",
    place_result = "thaumic-stone-furnace",
    stack_size = 50
  },  
  {
    type = "item",
    name = "infused-thaumic-stone-furnace",
    icon = "__base__/graphics/icons/stone-furnace.png",
    flags = {"goes-to-quickbar"},
    subgroup = "smelting-machine",
    order = "a[stone-furnace]",
    place_result = "infused-thaumic-stone-furnace",
    stack_size = 50
  },  
  {
    type = "item",
    name = "temp-aspect-machine",
    icon = "__base__/graphics/icons/chemical-plant.png",
    flags = {"goes-to-quickbar"},
    subgroup = "production-machine",
    order = "e[chemical-plant]",
    place_result = "temp-aspect-machine",
    stack_size = 10
  },
  {
    type = "item",
    name = "crucible",
	icon_size = 32,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/entity/Crucible.png",
    flags = {"goes-to-quickbar"},
    subgroup = "smelting-machine",
    order = "a[stone-furnace]",
    place_result = "crucible",
    stack_size = 50
  },  
  {
    type = "item",
    name = "TM-lab",
	icon_size = 32,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    flags = {"goes-to-quickbar"},
    subgroup = "production-machine",
    order = "g[TM-lab]",
    place_result = "TM-lab",
    stack_size = 10
  },  
  {
    type = "item",
	name = "air-shard",
	icon = "__Thaumaturgic-Machinations__/graphics/icons/item/air-shard.png",
	flags = {"goes-to-main-inventory"},
	subgroup = "raw-resource",
	order = "shard-air",
	stack_size = 100,
  },  
  {
    type = "item",
	name = "all-shard",
	icon = "__Thaumaturgic-Machinations__/graphics/icons/item/all-shard.png",
	flags = {"goes-to-main-inventory"},
	subgroup = "raw-resource",
	order = "shard-all",
	stack_size = 100,
  },  
  {
    type = "item",
	name = "earth-shard",
	icon = "__Thaumaturgic-Machinations__/graphics/icons/item/earth-shard.png",
	flags = {"goes-to-main-inventory"},
	subgroup = "raw-resource",
	order = "shard-earth",
	stack_size = 100,
  },  
  {
    type = "item",
	name = "entropy-shard",
	icon = "__Thaumaturgic-Machinations__/graphics/icons/item/entropy-shard.png",
	flags = {"goes-to-main-inventory"},
	subgroup = "raw-resource",
	order = "shard-entropy",
	stack_size = 100,
  },  
  {
    type = "item",
	name = "fire-shard",
	icon = "__Thaumaturgic-Machinations__/graphics/icons/item/fire-shard.png",
	flags = {"goes-to-main-inventory"},
	subgroup = "raw-resource",
	order = "shard-fire",
	stack_size = 100,
  },  
  {
    type = "item",
	name = "law-shard",
	icon = "__Thaumaturgic-Machinations__/graphics/icons/item/law-shard.png",
	flags = {"goes-to-main-inventory"},
	subgroup = "raw-resource",
	order = "shard-law",
	stack_size = 100,
  },  
  {
    type = "item",
	name = "water-shard",
	icon = "__Thaumaturgic-Machinations__/graphics/icons/item/water-shard.png",
	flags = {"goes-to-main-inventory"},
	subgroup = "raw-resource",
	order = "shard-water",
	stack_size = 100,
  },
  {
    type = "item",
	name = "vis-infused-brick",
	icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
	flags = {"goes-to-main-inventory"},
	subgroup = "raw-material",
	order = "vis-infused-brick",
	stack_size = 100,
  },
  {
    type = "item",
	name = "research-note",
	icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
	flags = {"goes-to-main-inventory"},
	subgroup = "TM-science",
	order = "research-note",
	stack_size = 100,
  },
  {
    type = "item",
	name = "alumentum",
	icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
	flags = {"goes-to-main-inventory"},
    fuel_category = "chemical",
    fuel_value = "20MJ",
	subgroup = "raw-material",
	order = "research-note",
	stack_size = 50,
  },
  {
    type = "item",
	name = "vis-infused-wood",
	icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
	flags = {"goes-to-main-inventory"},
    fuel_category = "Vis",
    fuel_value = "4MJ",
	subgroup = "raw-material",
	order = "vis-infused-wood",
	stack_size = 100,
  },
  {
    type = "item",
	name = "silverwood-seedling",
	icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
	flags = {"goes-to-main-inventory"},
	subgroup = "raw-material",
	order = "silverwood-seedling",
	stack_size = 100,
  },
  {
    type = "item",
	name = "raw-silverwood",
	icon = "__Thaumaturgic-Machinations__/graphics/icons/item/raw-silverwood.png",
	flags = {"goes-to-main-inventory"},
    fuel_category = "Vis",
    fuel_value = "10MJ",
	subgroup = "raw-material",
	order = "raw-silverwood",
	stack_size = 100,
  },
  {
    type = "item",
	name = "refined-silverwood",
	icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
	flags = {"goes-to-main-inventory"},
    fuel_category = "Vis",
    fuel_value = "15MJ",
	subgroup = "raw-material",
	order = "refined-silverwood",
	stack_size = 100,
  },
}
)