data:extend(
{
-- "Primal" Aspects
{
    type = "fluid",
    name = "Aer",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=1, g=1, b=0.4},
    flow_color = {r=1, g=1, b=0.4},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "Aqua",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=0.2, g=0.8, b=1},
    flow_color = {r=0.2, g=0.8, b=1},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "Ignis",
    default_temperature = 230,
    heat_capacity = "1KJ",
    base_color = {r=1, g=0, b=0},
    flow_color = {r=1, g=0, b=0},
    max_temperature = 1000,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.8,
},
{
    type = "fluid",
    name = "Ordo",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=0.9, g=0.9, b=0.9},
    flow_color = {r=0.9, g=0.9, b=0.9},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "Perditio",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=0.2, g=0.2, b=0.2},
    flow_color = {r=0.2, g=0.2, b=0.2},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "Terra",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=0, g=1, b=0},
    flow_color = {r=0, g=1, b=0},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},

-- Tier 1 Aspects

{
    type = "fluid",
    name = "Gelum",
    default_temperature = -15,
    heat_capacity = "0.001KJ",
    base_color = {r=0.8, g=0.8, b=0.9},
    flow_color = {r=0.8, g=0.8, b=0.9},
    max_temperature = 0,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "Lux",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=1, g=1, b=0.8},
    flow_color = {r=1, g=1, b=0.8},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "Metallum",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=0.6, g=0.6, b=0.6},
    flow_color = {r=0.6, g=0.6, b=0.6},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "Mortuus",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=0.4, g=0.4, b=0.4},
    flow_color = {r=0.4, g=0.4, b=0.4},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "Motus",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=0.55, g=0.55, b=0.55},
    flow_color = {r=0.55, g=0.55, b=0.55},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "Permutatio",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=0.2, g=0.4, b=0},
    flow_color = {r=0.2, g=0.4, b=0},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "Potentia",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=0.4, g=1, b=1},
    flow_color = {r=0.4, g=1, b=1},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "Vacuous",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=0.1, g=0.1, b=0.1},
    flow_color = {r=0.1, g=0.1, b=0.1},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "Vitae",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=1, g=0.2, b=0.6},
    flow_color = {r=1, g=0.2, b=0.6},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "Vitreus",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=0, g=1, b=1},
    flow_color = {r=0, g=1, b=1},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},

-- Tier 2 Aspects

{
    type = "fluid",
    name = "Auram",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=1, g=0.6, b=1},
    flow_color = {r=1, g=0.6, b=1},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "Bestia",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=0.6, g=0.4, b=0},
    flow_color = {r=0.6, g=0.4, b=0},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "Electrum",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=0.4, g=1, b=1},
    flow_color = {r=0.4, g=1, b=1},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "Examinis",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=0.3, g=0.3, b=0},
    flow_color = {r=0.3, g=0.3, b=0},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "Fames",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=0.8, g=0, b=0},
    flow_color = {r=0.8, g=0, b=0},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "Herba",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=0.1, g=1, b=0.1},
    flow_color = {r=0.1, g=1, b=0.1},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "Instrumentum",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=0, g=0, b=1},
    flow_color = {r=0, g=0, b=1},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "Iter",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=1, g=0.1, b=0.45},
    flow_color = {r=1, g=0.1, b=0.45},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "Machina",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=0.45, g=0.45, b=0.45},
    flow_color = {r=0.45, g=0.45, b=0.45},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "Magneto",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=0.25, g=0.25, b=0.25},
    flow_color = {r=0.25, g=0.25, b=0.25},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "Radio",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=0.55, g=1, b=0.1},
    flow_color = {r=0.5, g=1, b=0.1},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "Spiritus",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=0.75, g=0.75, b=0.75},
    flow_color = {r=0.75, g=0.75, b=0.75},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "Tempus",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=0.8, g=0.4, b=1},
    flow_color = {r=0.8, g=0.4, b=1},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "Tenebrae",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=0, g=0, b=0},
    flow_color = {r=0, g=0, b=0},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "Vinculum",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=1, g=0.75, b=0.5},
    flow_color = {r=1, g=0.75, b=0.5},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "Vitium",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=0.5, g=0, b=0.8},
    flow_color = {r=0.5, g=0, b=0.8},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "Volatus",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=0.9, g=0.9, b=0.9},
    flow_color = {r=0.9, g=0.9, b=0.9},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},

-- Tier 3 Aspects
{
    type = "fluid",
    name = "Alienis",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=0.3, g=0, b=0.5},
    flow_color = {r=0.3, g=0, b=0.5},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "Asidia",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=0.8, g=0.5, b=0},
    flow_color = {r=0.8, g=0.5, b=0},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "Avaritia",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=1, g=0.85, b=0},
    flow_color = {r=1, g=0.85, b=0},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "Aversio",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=1, g=0.3, b=0.3},
    flow_color = {r=1, g=0.3, b=0.3},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "Cognitio",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=1, g=0.7, b=0.7},
    flow_color = {r=1, g=0.7, b=0.7},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "Fabrico",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=0, g=0.7, b=0.5},
    flow_color = {r=0, g=0.7, b=0.5},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "Gula",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=.9, g=0.75, b=0},
    flow_color = {r=0.8, g=0.5, b=0},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "Humanus",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=1, g=0.9, b=0.9},
    flow_color = {r=1, g=0.9, b=0.9},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "Praemundio",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=0.4, g=0.5, b=1},
    flow_color = {r=0.4, g=0.5, b=1},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "Sensus",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=0, g=0.4, b=1},
    flow_color = {r=0, g=0.4, b=1},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "Superbia",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=1, g=0, b=1},
    flow_color = {r=1, g=0, b=1},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "Infernus",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=1, g=0.25, b=0},
    flow_color = {r=1, g=0.25, b=0},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "Invidia",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=0, g=0.9, b=0},
    flow_color = {r=0, g=0.9, b=0},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "Ira",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=0.9, g=0, b=0},
    flow_color = {r=0.9, g=0, b=0},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},
{
    type = "fluid",
    name = "Luxuria",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=1, g=0.7, b=0.7},
    flow_color = {r=1, g=0.7, b=0.7},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},
--[[
{
    type = "fluid",
    name = "Nebrisium",
    default_temperature = 25,
    heat_capacity = "0.1KJ",
    base_color = {r=1, g=0.9, b=0.2},
    flow_color = {r=1, g=0.9, b=0.2},
    max_temperature = 100,
    icon = "__Thaumaturgic-Machinations__/graphics/icons/WIP.png",
    pressure_to_speed_ratio = 1,
    flow_to_energy_ratio = 0.59,
},

]]--
})