if not TM then TM = {} end
require("prototypes.technology")
require("prototypes.TM-Aspect-Master")
require("TM-functions")
require("prototypes.TM-Aspect-Tree-Master")
require("prototypes.TM-Aspect-Distillation-raw")
require("prototypes.recipes")
require("prototypes.TM-Vanilla-Deconstruct")
require("prototypes.entities")
require("prototypes.item")
require("prototypes.categories")
require("prototypes.TM-item-aspects")
require("prototypes.TM-Modules")